### ISSUE TITLE
ys module path is now broken

### ISSUE THREAD

**Issue by vanderwb** [NCAR/HPCinstall#80]
I'm not sure when the change happened, but the 1.1 YS install now gives the wrong CDEP module path:

HPCI_MOD_DIR_CDEP = /glade/apps/opt/modulefiles/ys/intel/

**Comment by davidedelvento** [comment]
Fixed by aef23db6e5c43833b55d893314b3999369ce3dcd released as v1.2, installed on ys already and being installed on Cheyenne now
