### ISSUE TITLE
Shared scratch issues

### ISSUE THREAD

**Issue by vanderwb** [NCAR/HPCinstall#83]
Now that scratch is shared between the systems, there are potential path issues. The biggest one I see is the MOD dir pointing to /glade/scratch/$USER/test_installs/modulefiles/. Maybe there could be a ysmodules and chmodules (and lamodules and jsmodules if desired) instead of "modulefiles" in the test_installs directory.

**Comment by davidedelvento** [comment]
This is partially configurable, and I'll switch it to be fully configurable in the next release. I'm inclined to have the default configuration set to either `/glade/scratch/$USER/MYSTRING/test_installs/` or `/glade/scratch/$USER/test_installs/MYSTRING/` where MYSTRING is something like `ch` or `ys` or more verbose variants. Two questions:

* preferences?

* do you think you'll need it urgently?

**Comment by vanderwb** [comment]
1. Slight preference for the former, but it doesn't really matter.
2. I have nothing to install at the moment, but it would be nice to have for the next time I do so that I don't have to play symlink-foo to avoid contaminating module repos. So not urgent but very nice to have.

**Comment by davidedelvento** [comment]
Solved by PR #86 thanks @vanderwb
