### ISSUE TITLE
Source error could be clearer

### ISSUE THREAD

**Issue by vanderwb** [NCAR/HPCinstall#87]
Currently, if you specify a source file that cannot be found, you get the error:

`ERROR: Either or both the '#HPCI -u URL' and '#HPCI -a source.tgz' must be provided`

It would be clearer if the message stated that the file could not be found, rather than making it sound like the statement isn't there.

**Comment by davidedelvento** [comment]
Alright. For my records, there was also a similar problem when no directives were specified some confusing messages is thrown out, so I have to check that one too when I'll be fixing this

**Comment by davidedelvento** [comment]
Fixed by 318bc9e
