### ISSUE TITLE
Is HPCinstall meant to support Python 3?

### ISSUE THREAD

**Issue by andersy005** [NCAR/HPCinstall#89]
I am getting this syntax error. I am using Python3.6 

![hpc](https://user-images.githubusercontent.com/13301940/28677620-469fab12-72ab-11e7-9d88-3ff6e9178c29.jpeg)

**Comment by davidedelvento** [comment]
Nope you have to use python 2 to run it. Maybe the shebang should be changed to

```
#!/usr/bin/env python2
```

**Comment by andersy005** [comment]
Great! I switched to python2 and it works. 

Are there any plans of adding Python3 support ?

**Comment by davidedelvento** [comment]
I'm not opposed to it, but I'm not doing the porting myself at the moment.
