### ISSUE TITLE
How to change the HPCI_SW_DIR env variable?

### ISSUE THREAD

**Issue by andersy005** [NCAR/HPCinstall#93]
I am trying to tell hpcinstall  to change the `HPCI_SW_DIR` environment variable. I have tried the instructions from the docs without success. I am clearly missing something. 

One of the solutions explored is setting the `HPCI_TEST_BASEPATH` environment variable to `export HPCI_TEST_BASEPATH='/glade/p/work/abanihi/cheyenne/software/`.

However, HPCinstall is still using the following:

```bash
Setting environmental variables:
HPCI_SW_DIR       = /glade/scratch/abanihi/ch/test_installs/conda/4.3.30/
HPCI_SW_NAME      = conda
HPCI_SW_VERSION   = 4.3.30
HPCI_MOD_DIR      = /glade/scratch/abanihi/ch/test_installs/modulefiles/
HPCI_MOD_DIR_IDEP = /glade/scratch/abanihi/ch/test_installs/modulefiles/idep/
HPCI_MOD_DIR_CDEP = not_compiler_dependent
HPCI_MOD_PREREQ   = 
```

What  am I missing?

**Comment by davidedelvento** [comment]
Mmm, not sure. I'd need to look at the source code, but I'm not feeling too well and leaving for the day. Try if you can figure out yourself by looking at the source code, otherwise ping me again in a couple of days.

**Comment by andersy005** [comment]
I will let you know if I figure something out. In the meantime, I hope you get to feeling better soon.

**Comment by davidedelvento** [comment]
Mmmm, I cannot reproduce this issue:

```
$ export HPCI_TEST_BASEPATH='/glade/p/work/abanihi/cheyenne/software/'

$ ./hpcinstall.py install-hpcinstall 

HPCI_SW_DIR       = /glade/p/work/abanihi/cheyenne/software/hpcinstall/1.2.6/
HPCI_SW_NAME      = hpcinstall
HPCI_SW_VERSION   = 1.2.6
HPCI_MOD_DIR      = /glade/p/work/abanihi/cheyenne/software/modulefiles/
HPCI_MOD_DIR_IDEP = /glade/p/work/abanihi/cheyenne/software/modulefiles/idep/
HPCI_MOD_DIR_CDEP = not_compiler_dependent
HPCI_MOD_PREREQ   = 
Running ./install-hpcinstall...
Fake module implementation
Found /usr/bin/git
mkdir: cannot create directory ‘/glade/p/work/abanihi/cheyenne/software/hpcinstall/1.2.6/’: Permission denied
```

What command are you exactly issuing? By design this feature is not supported in conjunction with the `-c`

**Comment by andersy005** [comment]
Thanks, @davidedelvento. I (hopefully :) ) figured out what part I was missing. 

I was  setting `HPCI_TEST_BASEPATH` as a temporary environment variable using `$export`, which I believe was being overwritten whenever a new session was initiated by HPCinstall install script. Everything worked fine once I added the `HPCI_TEST_BASEPATH` to `.bashrc`.
